theme: jekyll-theme-minimal
title: BGH Atlas
description: |
  <br><br>The Atlas is a top-level visual summary of end-member numerical models that the BGH is created.
  <br><br>
  <p><a href="https://github.com/rsbyrne/demonstration"><h2><b>Contribute to the Atlas</b></h2></a></p>
  <p>1. Clone the repository</p>
  <p>2. Go to the "pages" directory and make a copy of the "example" folder</p>
  <p>3. Open up the Jupyter notebook and follow the instructions (make sure to run the code at the bottom when you are finished!)</p>
  <p>4. Push your changes back up to the repository.</p>
logo: site_resources/BasinGensisHub.png
paginate: 2
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

analytics: UA-143750223-1

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

